package dotsync:plugin;

interface operating-systems {
  enum operating-system {
    unspecified-o-s,
    mac-o-s,
    windows
  }

  enum linux-distribution {
    unspecified-distro,
    debian,
    ubuntu,
    fedora,
    cent-o-s,
    r-h-e-l,
    arch,
    manjaro,
    open-s-u-s-e,
    gentoo,
    alpine,
    solus,
    mint,
    pop-o-s,
    nix-o-s,
    void,
    kali
  }
}

interface host {
  record command-output {
    stdout: string,
    stderr: string,
    exit-code: option<s32>,
  }

  subrun: func(plugin-id: string, config-json: string) -> result<_, string>;
  run-command: func(command: string, env: list<tuple<string, string>>) -> result<command-output, string>;
  resolve-path: func(path: string) -> result<string, string>;
  confirm: func(message: string, default: bool) -> result<bool, string>;
}

world plugin {
  use operating-systems.{operating-system, linux-distribution};

  import host;

  export id: func() -> string;
  export description: func() -> string;
  export dependencies: func() -> list<string>;

  export supported-operating-systems: func() -> list<operating-system>;
  export supported-linux-distributions: func() -> list<linux-distribution>;

  export import-config: func() -> result<string, string>;
  export run: func(config-json: string) -> result<_, string>;
}
