[alias]
format          = "fmt"
format-check    = "fmt --check"
lint            = "clippy --all-targets --all-features -- -D warnings"
test-cover      = "llvm-cov --all --all-features --lcov --output-path lcov.info"
test-cover-html = "llvm-cov --all --all-features --html --output-dir target/coverage"
